-- Create admin user for testing
INSERT INTO public.companies (
  email,
  password,
  company_name,
  ceo_name,
  manager_name,
  manager_position,
  phone_number,
  industry,
  headquarters_country,
  headquarters_city,
  founding_year,
  employee_count,
  revenue_scale,
  main_products,
  target_market,
  competitive_advantage,
  company_vision,
  website,
  is_approved,
  is_admin,
  created_at,
  updated_at
) VALUES (
  'admin@example.com',
  'admin123',
  'KnowWhere Bridge Admin',
  'Admin User',
  'System Administrator',
  'Admin',
  '+82-10-0000-0000',
  'Technology',
  'South Korea',
  'Seoul',
  '2023',
  '10-50',
  '1억원 이하',
  'Global Business Matching Platform',
  'Global Companies',
  'AI-powered matching system',
  'Connect businesses worldwide',
  'https://knowwhere-bridge.com',
  true,
  true,
  now(),
  now()
) ON CONFLICT (email) DO UPDATE SET
  password = EXCLUDED.password,
  is_approved = true,
  is_admin = true,
  updated_at = now();

-- Create a test regular user as well
INSERT INTO public.companies (
  email,
  password,
  company_name,
  ceo_name,
  manager_name,
  manager_position,
  phone_number,
  industry,
  headquarters_country,
  headquarters_city,
  founding_year,
  employee_count,
  revenue_scale,
  main_products,
  target_market,
  competitive_advantage,
  company_vision,
  website,
  is_approved,
  is_admin,
  created_at,
  updated_at
) VALUES (
  'user@example.com',
  'user123',
  'Test Company Ltd.',
  'Test CEO',
  'Test Manager',
  'Manager',
  '+82-10-1234-5678',
  'Manufacturing',
  'South Korea',
  'Busan',
  '2020',
  '50-100',
  '10억원 이상',
  'Test Products',
  'Asia Pacific',
  'Quality and Innovation',
  'Leading the industry',
  'https://testcompany.com',
  true,
  false,
  now(),
  now()
) ON CONFLICT (email) DO UPDATE SET
  password = EXCLUDED.password,
  is_approved = true,
  updated_at = now();